
---
- hosts: webservers
  become: true
  vars:
    ansible_become_pass: 123456789
  tasks:
 
  - name: copyWebapp 
    copy:
      src: /var/lib/jenkins/workspace/TestMavenProject/webapp/target
      dest: /usr/share/tomcat/webapps/

